### ISSUE TITLE
dap-tooltip-mode suppress tooltip-mode

### ISSUE THREAD

**Issue by seagle0128** [emacs-lsp/dap-mode#314]
- Description:
   After enabling `dap-tooltip-mode`, the original tooltip cannot be displayed. Disable and re-enable `tooltip-mode`, it works again. 

I checked the `tooltip-functions`, the value is:
```elisp
(dap-tooltip-tips
 tooltip-help-tips)
```

The correct value should be:
```elisp
(tooltip-help-tips
dap-tooltip-tips)
```

Please check if it's an issue. Thanks!

- Env:
1. macOS Catalina
1. GNU Emacs 28.0.50
1. [Centaur Emacs](https://github.com/seagle0128/.emacs.d/)

**Comment by bk138** [comment]
Same here. FWIW, here's a `.emacs` to repro:

```
;;
;; bootstrap use-package as per http://cachestocaches.com/2015/8/getting-started-use-package/
;;
(require 'package)
(setq package-enable-at-startup nil)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(if (string-equal system-type "gnu/linux")
    (setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")) ; make default https elpa usable again
(package-initialize)
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

;; configure use-package
(eval-when-compile
  (require 'use-package)
  (setq use-package-compute-statistics t)
  (require 'use-package-ensure)
  (setq use-package-always-ensure t))

;; make elpa usable again
(use-package gnu-elpa-keyring-update)

;;
;; LSP
;;
(use-package lsp-mode
  :hook (prog-mode . lsp)
)

(use-package dap-mode)

(use-package ccls
  :defer t) ; C Language Server
```

Once you open a C file, lsp and dap-mode kick in, no tooltips anymore.

**Comment by nbfalcon** [comment]
I think this is caused by `dap-tooltip-mode`, which uses `add-hook`, which by default pushes to the front. This could probably be fixed by specifying the depth parameter. Why do you think the dap-mode tooltip function should have a lower priority?

**Comment by seagle0128** [comment]
Any update, pls?

**Comment by seagle0128** [comment]
I can confirm the patch fixes the issue. I am closing it.

**Comment by seagle0128** [comment]
I found the tooltip still doesn't works for the buffers while enable `lsp-mode` and `dap-mode`, while works well for other buffers, e.g. elisp buffers. `dap-tooltip-mode` still suppress `tooltip-mode` in mode-line.

**Comment by seagle0128** [comment]
@wyuenho It makes sense. So will file another issue to track?

**Comment by seagle0128** [comment]
IMO, it is. When I am coding and open a buffer with enabling `lsp-mode`, `dap-mode` and `dap-tooltip-mode`, but I am not debugging, then all tooltips won't be displayed. I think it's not a proper behavior.

**Comment by seagle0128** [comment]
Then I am closing now. And will reopen if anyone thinks it's an issue.
